source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-theme-chirpy", "~> 7.3"

# Chirpy theme plugins
gem "jekyll-paginate"
gem "jekyll-redirect-from"
gem "jekyll-archives"
gem "jekyll-sitemap"
gem "jekyll-include-cache"